version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gocritic
  exclusions:
    generated: strict
    paths:
      - gen/
      - examples/

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: strict
    paths:
      - gen/
      - examples/
